# Generated by Django 3.1.3 on 2020-11-24 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Заболевание',
                'verbose_name_plural': 'Заболевания',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='имя человека')),
                ('age', models.IntegerField(verbose_name='возраст')),
                ('dateofbirth', models.DateField(verbose_name='дата рождения')),
                ('sex', models.CharField(blank=True, choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=1)),
            ],
            options={
                'verbose_name': 'Человек',
                'verbose_name_plural': 'Люди',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
                ('manufacturer', models.CharField(max_length=200, null=True, verbose_name='производитель')),
                ('protection_period', models.DateField(null=True, verbose_name='срок действия')),
                ('administration_schedule', models.TextField(null=True, verbose_name='схема введения')),
                ('age', models.IntegerField(null=True, verbose_name='возраст')),
                ('efficiency_percent', models.IntegerField(null=True, verbose_name='эффективность')),
                ('side_effects', models.TextField(null=True, verbose_name='побочные эффекты')),
                ('price', models.IntegerField(null=True, verbose_name='цена')),
                ('currency_type', models.CharField(choices=[('RUB', 'Ruble'), ('EUR', 'Euro'), ('USD', 'US Dollar')], default=('EUR', 'Euro'), max_length=10, verbose_name='тип валюты')),
                ('comments', models.TextField(null=True, verbose_name='комментарий')),
                ('is_hidden', models.BooleanField(default=False, null=True)),
                ('is_produced', models.BooleanField(default=True, null=True)),
                ('desease', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vaccineapp.desease', verbose_name='заболевание')),
            ],
            options={
                'verbose_name': 'Вакцина',
                'verbose_name_plural': 'Вакцины',
            },
        ),
        migrations.CreateModel(
            name='UserPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccineapp.person')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccineapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='PersonVaccine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_expire', models.DateField(null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccineapp.person')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccineapp.vaccine')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccineapp.user'),
        ),
        migrations.AddField(
            model_name='person',
            name='vaccines',
            field=models.ManyToManyField(to='vaccineapp.Vaccine'),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('vaccines', models.ManyToManyField(to='vaccineapp.Vaccine')),
            ],
            options={
                'verbose_name': 'Коллекция',
                'verbose_name_plural': 'Коллекции',
            },
        ),
    ]
