# Generated by Django 3.1.3 on 2020-11-24 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccineapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='administration_schedule',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='схема введения'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='age',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='возраст'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='comments',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='комментарий'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='desease',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='vaccineapp.desease', verbose_name='заболевание'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='efficiency_percent',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='эффективность'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='is_hidden',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='is_produced',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='manufacturer',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='производитель'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='price',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='protection_period',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='срок действия'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='side_effects',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='побочные эффекты'),
        ),
    ]
