# Generated by Django 3.1.3 on 2020-12-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccineapp', '0002_auto_20201205_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='diseases',
            field=models.ManyToManyField(blank=True, null=True, to='vaccineapp.Disease', verbose_name='заболевания'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='vaccines',
            field=models.ManyToManyField(blank=True, null=True, to='vaccineapp.Vaccine', verbose_name='вакцины'),
        ),
    ]
