# Generated by Django 3.1.3 on 2020-12-06 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccineapp', '0003_auto_20201205_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='personvaccine',
            name='disease',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vaccineapp.disease'),
        ),
        migrations.AlterField(
            model_name='personvaccine',
            name='vaccine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vaccineapp.vaccine'),
        ),
    ]
