# Generated by Django 3.1.3 on 2020-11-24 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccineapp', '0003_auto_20201124_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='age',
        ),
    ]
