# Generated by Django 3.1.3 on 2020-12-06 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccineapp', '0005_auto_20201206_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='diseases',
        ),
        migrations.RemoveField(
            model_name='person',
            name='vaccines',
        ),
        migrations.RemoveField(
            model_name='personvaccine',
            name='person',
        ),
        migrations.AddField(
            model_name='person',
            name='person_vaccines',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vaccineapp.personvaccine', verbose_name='вакцины человека'),
        ),
    ]
