# Generated by Django 3.1.3 on 2020-12-06 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccineapp', '0006_auto_20201206_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='person_vaccines',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vaccineapp.personvaccine', verbose_name='вакцины человека'),
        ),
    ]
