# Generated by Django 3.1.3 on 2020-12-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccineapp', '0007_auto_20201206_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='person_vaccines',
        ),
        migrations.AddField(
            model_name='person',
            name='person_vaccines',
            field=models.ManyToManyField(blank=True, to='vaccineapp.PersonVaccine', verbose_name='вакцины человека'),
        ),
    ]
