# Generated by Django 3.1.3 on 2020-12-06 10:32

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('vaccineapp', '0008_auto_20201206_1500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personvaccine',
            options={'verbose_name': 'Вакцины человека', 'verbose_name_plural': 'Вакцины человека'},
        ),
        migrations.AlterField(
            model_name='person',
            name='person_vaccines',
            field=models.ManyToManyField(to='vaccineapp.PersonVaccine', verbose_name='вакцины человека'),
        ),
        migrations.AlterField(
            model_name='personvaccine',
            name='date_expire',
            field=models.DateField(null=True, verbose_name='Срок действия (до)'),
        ),
        migrations.AlterField(
            model_name='personvaccine',
            name='disease',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vaccineapp.disease', verbose_name='заболевание'),
        ),
        migrations.AlterField(
            model_name='personvaccine',
            name='vaccine',
            field=smart_selects.db_fields.GroupedForeignKey(group_field='Disease', null=True, on_delete=django.db.models.deletion.CASCADE, to='vaccineapp.vaccine', verbose_name='вакцина'),
        ),
    ]
