# Generated by Django 3.1.3 on 2020-12-06 10:35

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('vaccineapp', '0009_auto_20201206_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personvaccine',
            name='disease',
            field=smart_selects.db_fields.GroupedForeignKey(group_field='Vaccine', null=True, on_delete=django.db.models.deletion.CASCADE, to='vaccineapp.disease', verbose_name='заболевание'),
        ),
        migrations.AlterField(
            model_name='personvaccine',
            name='vaccine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vaccineapp.vaccine', verbose_name='вакцина'),
        ),
    ]
