# Generated by Django 3.1.3 on 2020-12-06 10:36

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('vaccineapp', '0010_auto_20201206_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personvaccine',
            name='disease',
            field=smart_selects.db_fields.GroupedForeignKey(group_field='vaccines', null=True, on_delete=django.db.models.deletion.CASCADE, to='vaccineapp.disease', verbose_name='заболевание'),
        ),
    ]
