# Generated by Django 3.1.3 on 2020-12-06 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccineapp', '0011_auto_20201206_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personvaccine',
            name='disease',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vaccineapp.disease', verbose_name='заболевание'),
        ),
    ]
