# Generated by Django 3.1.3 on 2020-12-06 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccineapp', '0012_auto_20201206_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='person_vaccines',
        ),
        migrations.AddField(
            model_name='personvaccine',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vaccineapp.person', verbose_name='человек'),
        ),
    ]
