# Generated by Django 3.1.3 on 2020-12-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccineapp', '0013_auto_20201206_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], default='M', max_length=1, verbose_name='пол'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='protection_period',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='срок действия (мес)'),
        ),
    ]
