# Generated by Django 3.1.3 on 2020-12-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccineapp', '0014_auto_20201207_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personvaccine',
            name='date_expire',
        ),
        migrations.AddField(
            model_name='personvaccine',
            name='vaccination_date',
            field=models.DateField(null=True, verbose_name='Дата вакцинации'),
        ),
    ]
