# Generated by Django 3.1.3 on 2020-12-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccineapp', '0015_auto_20201207_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personvaccine',
            name='vaccination_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата вакцинации'),
        ),
    ]
